### PR TITLE
Link with -pthreads when using Clang

### PR DESCRIPTION
**Pull request by diizzyy**
This fixes linking issue on FreeBSD

### CODE REVIEW

**Comment by diizzyy** [comment]
This likely an incorrect "hack" as it does depend on pthread and should always link to it properly even if it might work without it in some cases

**Comment by complexlogic** [comment]
@diizzyy Regarding BSD support: I believe there is an issue with the home directory search path for the scan presets. The [code](https://github.com/complexlogic/rsgain/blob/master/src/easymode.cpp#L412-L420) assumes either `__APPLE__` or `__linux` will be defined for Unix systems, but I believe this is not the case for BSD. Could you confirm? If that is the case, what would be a good place to search to user scan presets on BSD? Would `~/.config/rsgain/presets` work? That is what is being done for Linux.

**Comment by diizzyy** [comment]
That's correct, see https://sourceforge.net/p/predef/wiki/OperatingSystems/ for example

Rsgain is already packaged (https://cgit.freebsd.org/ports/tree/audio/rsgain) and presets are located in /usr/local/share/rsgain/presets/ which follows FreeBSD's directory structure and works as intended. The local path you suggested sounds good if you want local ones per user basis.

I would however expect rsgain to bail out (exit with error message) when you specify a non existant present not just silently continue.

While we're on the FreeBSD topic, Jason (the maintainer) also made a patch you might want to look into.
https://cgit.freebsd.org/ports/tree/audio/rsgain/files/patch-src_tag.cpp . I asked him to submit upstream but he appears to a bit busy right now.

**Comment by diizzyy** [comment]
@complexlogic In case you missed

**Comment by complexlogic** [comment]
I think it would be best to open a new issue "BSD Support" to track these various issues. Could you do that?

**Pull request merged**
